/**
 * Thin client for the dsec-api public feed (`/website/*`, no auth) — the same
 * backend the public site and committee hub read. This proves the portal's
 * wiring to the shared API (which itself reads the shared Neon DB). Feature
 * pages will add authenticated loaders later.
 *
 * Every loader returns `null` on any failure (unset DSEC_API_URL, network error,
 * bad status) so the UI can show a friendly fallback instead of crashing.
 */

export type PortalEvent = {
  slug: string;
  title: string;
  date: string | null; // ISO date (YYYY-MM-DD)
  venue: string | null;
  type: string | null;
  upcoming: boolean;
};

function apiBase(): string | null {
  const b = process.env.DSEC_API_URL;
  return b ? b.replace(/\/+$/, "") : null;
}

/** Base + bearer key for AUTHENTICATED dsec-api calls (server-only). null when
 *  either env var is unset, so callers degrade gracefully. The key must never
 *  reach the browser — only ever read inside server components / actions. */
export function apiAuth(): { base: string; key: string } | null {
  const base = apiBase();
  const key = process.env.DSEC_API_KEY;
  return base && key ? { base, key } : null;
}

/** The member's digital-membership-card data (code + QR), generated by dsec-api. */
export type MemberVerification = {
  memberId: number;
  code: string; // "DSEC-7K2P-9XQ4"
  fullName: string | null;
  membershipType: string | null;
  memberSince: string | null; // ISO date
  isCurrent: boolean;
  verifyUrl: string;
  qrSvg: string | null; // inline SVG, server-trusted
};

/** Public scan/verify result for a shown membership code. */
export type VerifyResult = {
  valid: boolean;
  memberId: number | null;
  fullName: string | null;
  membershipType: string | null;
  memberSince: string | null;
  isCurrent: boolean;
};

/**
 * Fetch a verified member's own card data (code + QR). Authenticated (needs a
 * read-scoped DSEC_API_KEY). Returns null on any failure so the dashboard shows
 * a graceful fallback instead of crashing.
 */
export async function getMemberVerification(
  memberId: number,
): Promise<MemberVerification | null> {
  const env = apiAuth();
  if (!env) return null;
  try {
    const res = await fetch(`${env.base}/members/${memberId}/verification-code`, {
      headers: { Authorization: `Bearer ${env.key}` },
      cache: "no-store", // per-member, authed — always live
    });
    if (!res.ok) {
      if (process.env.NODE_ENV !== "production") {
        console.warn(`[dsec-api] GET /members/${memberId}/verification-code → ${res.status}`);
      }
      return null;
    }
    const j = await res.json();
    return {
      memberId: j.member_id,
      code: j.code,
      fullName: j.full_name ?? null,
      membershipType: j.membership_type ?? null,
      memberSince: j.member_since ?? null,
      isCurrent: !!j.is_current,
      verifyUrl: j.verify_url,
      qrSvg: j.qr_svg ?? null,
    };
  } catch (err) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`[dsec-api] verification-code failed: ${(err as Error).message}`);
    }
    return null;
  }
}

/**
 * Resolve a shown membership code to its member (PUBLIC endpoint — no key).
 * Used by the /verify page when door staff scan/open a card's QR. Returns null
 * only when the API is unreachable; an unknown code resolves to `{valid:false}`.
 */
export async function verifyMemberCode(code: string): Promise<VerifyResult | null> {
  const base = apiBase();
  if (!base) return null;
  try {
    const res = await fetch(`${base}/members/verify/${encodeURIComponent(code)}`, {
      cache: "no-store", // door verification must be live
    });
    if (!res.ok) return { valid: false, memberId: null, fullName: null, membershipType: null, memberSince: null, isCurrent: false };
    const j = await res.json();
    return {
      valid: !!j.valid,
      memberId: j.member_id ?? null,
      fullName: j.full_name ?? null,
      membershipType: j.membership_type ?? null,
      memberSince: j.member_since ?? null,
      isCurrent: !!j.is_current,
    };
  } catch (err) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`[dsec-api] verify/${code} failed: ${(err as Error).message}`);
    }
    return null;
  }
}

/** Upcoming events from the shared API feed, soonest first. `null` on failure. */
export async function getUpcomingEvents(limit = 4): Promise<PortalEvent[] | null> {
  const base = apiBase();
  if (!base) return null;
  try {
    // 5-min cache; the feed is public and changes rarely.
    const res = await fetch(`${base}/website/events`, { next: { revalidate: 300 } });
    if (!res.ok) {
      if (process.env.NODE_ENV !== "production") {
        console.warn(`[dsec-api] GET /website/events → ${res.status}`);
      }
      return null;
    }
    const rows = (await res.json()) as PortalEvent[];
    return rows.filter((e) => e.upcoming).slice(0, limit);
  } catch (err) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`[dsec-api] GET /website/events failed: ${(err as Error).message}`);
    }
    return null;
  }
}
