"use client";

import { useCallback, useEffect, useId, useRef, useState } from "react";

/**
 * The member's digital membership card. A compact tile on the dashboard that
 * expands into a full-screen modal for showing at events / the door:
 *
 *   - the member's FACE PHOTO (uploaded at onboarding) so staff can match the
 *     person to the card at a glance,
 *   - a unique member code (generated by dsec-api) + a scannable QR that opens
 *     the public /verify page,
 *   - live membership status.
 *
 * Trial / not-yet-on-the-roster members get a "pending" card (photo + status,
 * but no code) so the surface is consistent while they're being verified.
 */

type Props = {
  name: string;
  photoUrl: string | null;
  status: "verified" | "trial";
  membershipType?: string | null;
  memberSince?: string | null; // ISO date
  /** Present only for a fully-active card (verified + on the roster). */
  code?: string | null;
  qrSvg?: string | null;
};

function fmtDate(iso?: string | null): string | null {
  if (!iso) return null;
  const d = new Date(`${iso}T00:00:00`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-AU", { month: "short", year: "numeric" });
}

function ExpandIcon() {
  return (
    <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3m13-5v3a2 2 0 0 1-2 2h-3" />
    </svg>
  );
}

function CloseIcon() {
  return (
    <svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M18 6 6 18M6 6l12 12" />
    </svg>
  );
}

/** The square face photo (or a lettered fallback if somehow missing). */
function Avatar({ photoUrl, name, size }: { photoUrl: string | null; name: string; size: number }) {
  if (photoUrl) {
    return (
      // eslint-disable-next-line @next/next/no-img-element -- remote Supabase URL; portal renders these as plain <img> (see next.config).
      <img
        src={photoUrl}
        alt={`${name}'s verification photo`}
        width={size}
        height={size}
        className="block border-[3px] border-paper object-cover"
        style={{ width: size, height: size, imageRendering: "auto" }}
      />
    );
  }
  return (
    <div
      className="flex items-center justify-center border-[3px] border-paper bg-panel-2 font-display font-bold text-paper/70"
      style={{ width: size, height: size, fontSize: size * 0.4 }}
      aria-hidden="true"
    >
      {(name.trim()[0] ?? "?").toUpperCase()}
    </div>
  );
}

export function VerificationCard(props: Props) {
  const { name, photoUrl, status, membershipType, memberSince, code, qrSvg } = props;
  const active = status === "verified" && !!code;
  const since = fmtDate(memberSince);

  const [open, setOpen] = useState(false);
  const closeBtnRef = useRef<HTMLButtonElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);
  const titleId = useId();

  const close = useCallback(() => setOpen(false), []);

  // While open: lock body scroll, focus the close button, ESC to close, and a
  // light focus trap so Tab stays inside the dialog. Restores on close/unmount.
  useEffect(() => {
    if (!open) return;
    const prevOverflow = document.body.style.overflow;
    const prevFocus = document.activeElement as HTMLElement | null;
    document.body.style.overflow = "hidden";
    closeBtnRef.current?.focus();

    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") {
        close();
        return;
      }
      if (e.key === "Tab" && dialogRef.current) {
        const f = dialogRef.current.querySelectorAll<HTMLElement>(
          'a[href],button:not([disabled]),[tabindex]:not([tabindex="-1"])',
        );
        if (f.length === 0) return;
        const first = f[0];
        const last = f[f.length - 1];
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    }
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
      prevFocus?.focus?.();
    };
  }, [open, close]);

  return (
    <>
      {/* --- Compact dashboard tile --- */}
      <div className="pixel-card-lg p-6">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-4">
            <Avatar photoUrl={photoUrl} name={name} size={64} />
            <div>
              <p className="eyebrow">Membership card</p>
              <p className="font-display text-lg font-bold">{name}</p>
              {status === "verified" ? (
                <p className="mt-0.5 font-display text-sm font-bold text-mint">✓ Active member</p>
              ) : (
                <p className="mt-0.5 font-display text-sm font-bold text-yellow">⏳ Being verified</p>
              )}
              {active ? (
                <p className="mt-1 font-mono text-xs tracking-[0.18em] text-paper/70">{code}</p>
              ) : status === "verified" ? (
                <p className="mt-1 text-xs text-paper/60">Your card is loading — check back in a moment.</p>
              ) : (
                <p className="mt-1 text-xs text-paper/60">Your card unlocks once your membership is verified.</p>
              )}
            </div>
          </div>

          {active && (
            <button type="button" onClick={() => setOpen(true)} className="btn btn-pink !text-sm shrink-0">
              <span className="inline-flex items-center gap-2">
                <ExpandIcon /> Show card
              </span>
            </button>
          )}
        </div>
      </div>

      {/* --- Full-screen modal --- */}
      {open && active && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center overflow-y-auto bg-void/95 p-4 backdrop-blur-sm"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) close();
          }}
        >
          <div
            ref={dialogRef}
            role="dialog"
            aria-modal="true"
            aria-labelledby={titleId}
            className="pixel-card-lg relative my-auto w-full max-w-sm bg-panel p-6 text-center"
          >
            <button
              ref={closeBtnRef}
              type="button"
              onClick={close}
              aria-label="Close membership card"
              className="absolute right-3 top-3 inline-flex h-9 w-9 items-center justify-center border-[3px] border-paper bg-void text-paper transition-colors hover:bg-pink"
            >
              <CloseIcon />
            </button>

            <p className="eyebrow">DSEC // Member</p>

            <div className="mt-4 flex justify-center">
              <Avatar photoUrl={photoUrl} name={name} size={120} />
            </div>

            <h2 id={titleId} className="mt-4 font-display text-2xl font-bold text-3d-pink">
              {name}
            </h2>
            <p className="mt-1 font-display text-sm font-bold text-mint">✓ Active member</p>
            <p className="mt-0.5 font-mono text-xs text-paper/60">
              {membershipType ? `${membershipType} · ` : ""}
              {since ? `Member since ${since}` : "Verified via DUSA"}
            </p>

            {/* QR — scannable; opens the public verify page. */}
            {qrSvg ? (
              <div className="mx-auto mt-5 w-full max-w-[220px] border-[3px] border-paper bg-white p-3 [&>svg]:block [&>svg]:h-auto [&>svg]:w-full">
                <span dangerouslySetInnerHTML={{ __html: qrSvg }} />
              </div>
            ) : null}

            {/* The human-readable code. */}
            <p className="mt-5 font-display text-3xl font-bold tracking-[0.12em] text-yellow">{code}</p>

            <p className="mt-4 text-sm text-paper/75">Show this at the door — staff scan the code to verify you.</p>
            <p className="mt-2 font-mono text-[11px] text-paper/45">Turn your screen brightness up for a faster scan.</p>

            <button type="button" onClick={close} className="btn btn-ghost mt-5 w-full !text-sm">
              Done
            </button>
          </div>
        </div>
      )}
    </>
  );
}
